### ISSUE TITLE
can you give some readme file or some paper related for your flowing project, and it looks interesting.

### ISSUE THREAD

**Issue by feilong0309** [ArnauPrat/flowing#1]
Dear sir,

I am also interested in clustering on the streaming graph. I am wondering whether you can give more detail about your flowing code.

Best wishes！
Jianpeng

**Comment by ArnauPrat** [comment]
Hi @feilong0309 
Unfortunately, this project was a small test I started and went nowhere. There is no paper and I even don't remember how far I went with it, so I cannot add a readme. I am sorry about that, but the best thing I can do is to delete the repository.

Best,
Arnau
